### ISSUE TITLE
vkhlf::setImageLayout dont support vk::ImageSubresourceRange

### ISSUE THREAD

**Issue by LuisAntonRebollo** [nvpro-pipeline/VkHLF#15]
Working with Vulkan for the first time, sorry if i misunderstood the API :)

I'm trying to upload a texture to gpu, but the function _vkhlf::setImageLayout_ don't expose any way to work with mipmaps or layers. I changed function declaration from _vk::ImageAspectFlags aspectMask_ to _const vk::ImageSubresourceRange &subResourceRange_

Is the correct way to use VkHLF or i missed something?

Thx for all your open source Vk contibutions.

**Comment by asuessenbach** [comment]
This has been resolved by pull request #19.

**Comment by LuisAntonRebollo** [comment]
Thx :)
