### ISSUE TITLE
using weak_ptr to cache queues leads to problems

### ISSUE THREAD

**Issue by ratchetfreak** [nvpro-pipeline/VkHLF#2]
If the queue has a submission pending a fence and gets destroyed the submission info also gets released even if the fence hasn't been triggered.

Then if you get the queue again from the Device the queue will appear to have no submissions:

```C++
{
  auto queue = device->getQueue(0,0);
  queue->submit(submit,null_ptr);
}
//queue is destroyed and submit info is lost regardless of whether the fence was triggered
{
  auto queue = device->getQueue(0,0);
  // no submit info available
}
```

Currently it's not a problem because the information is never used. But if it's never used then why keep it in the first place?

---

Related to this is that getting the same queue from 2 different threads is not thread-safe due to the lazy initialization.

**Comment by mtavenrath** [comment]
releaseResources needs the fences of the submitInfos to release the resourceTracker objects. 

The bug is that the destructor of the Queue has to wait until all fences have been triggered before calling releaseResources. Otherwise the Queue will release the resources even if the GPU is not finished with the work.

Code using device->getQueue(0,0) will vanish since it's not safe. Nevertheless this means that the application should not get a queue temporary and forget about it directly, but keep it alive to avoid CPU stalls in the current implementation. A more clean implementation will move releaseResources to another place/another thread so that it's indepdent of the queue.

**Comment by ratchetfreak** [comment]
Currently the [destructor of Queue](https://github.com/nvpro-pipeline/VkHLF/blob/master/vkhlf/src/Queue.cpp#L202-L205) does not wait on any fences. 

It just calls releaseResources which flushes the sets but then the destructor of std::map kicks in, which doesn't care about the fences. It just sees the `shared_ptr`s and decrements the refcount, then it goes ahead and deletes the std::vectors.

**Comment by mtavenrath** [comment]
And that's where the bug is ;-)

**Comment by ratchetfreak** [comment]
Or alternatively tie the lifetimes of the queue objects to the lifetime of device and use the aliasing constructor of shared_ptr. It'll requires that the Reference to Device is removed from queue and replaced with a weak_ptr or raw pointer.

```C++
return shared_ptr( shared_from_this(this), &m_queues[familyIndex][queueIndex]);
```

**Comment by mtavenrath** [comment]
This seems to be the perfect solution since Queues and Devices have the exact same lifetime. I'll take a look at the required code changes.

**Comment by ratchetfreak** [comment]
the code changes would be pretty simple:

in the Device constructor you would replace the last for loop with:

```C++
    for (uint32_t i = 0; i<createInfo.queueCreateInfoCount; i++)
    {
          m_queues[i].reserve(createInfo.pQueueCreateInfos[i].queueCount);
          for (uint32_t j = 0; j<createInfo.pQueueCreateInfos[i].queueCount; j++)
          {
                m_queues[i].emplace_back(this, i, j);
          }
    }
```

change getQueue to: 

```C++
return shared_ptr( shared_from_this(), &m_queues[familyIndex][queueIndex]);
```

change m_queues to 

```C++
std::vector<std::vector<Queue>> m_queues;
```

And I already mentioned what would need to change in Queue. Though the code that gets a Device from Queue would also need to change.

**Comment by asuessenbach** [comment]
Issue fixed. Closing.
