### ISSUE TITLE
New SDK Compatibility

### ISSUE THREAD

**Issue by parsaiej** [nvpro-pipeline/VkHLF#27]
I noticed that the newer versions of the Vulkan SDK (1.0.42.1) moved the libraries from Bin/Bin32 -> Lib/Lib32. So people with the newer SDK may need to modify FindVulkan.cmake to account for this. Also had to replace VK_NULL_HANDLE with nullptr.

**Comment by acdemiralp** [comment]
See #30

**Comment by asuessenbach** [comment]
Resolved by commit #30.
