### ISSUE TITLE
Case sensitivity in CMakeLists.txt on Linux systems

### ISSUE THREAD

**Issue by Delwin9999** [nvpro-pipeline/VkHLF#4]
samples/01_window/CMakeLists.txt:32 has the line find_package(glfw3 3.2 REQUIRED) which will fail on case sensitive systems because the corresponding file is FindGLFW3.cmake.  The easy fix is to change the CMakeLists.txt to use  find_package(GLFW3 3.2 REQUIRED).  Unfortunately I can't submit pull requests from where I am but when I get to a place where I can I'll throw that up for you.

**Comment by mtavenrath** [comment]
Thanks for reporting the issue. 

Pull requests require an contributor agreement which is more work than just fixing the issue. I'll take care of the issue.

**Comment by Delwin9999** [comment]
I'm going to be working with this quite a bit in the near future so I'll start the process of a contributor agreement.  As a side note the vkhlf/src/CMakeLists.txt is windows specific at the moment.  I'll put together a cross platform version (at least one that can handle Linux/GCC) while I'm getting the paperwork in order.  When it's all done I'll throw a pull request for full cross platform support.

**Comment by mtavenrath** [comment]
Fixed, closing.
