### ISSUE TITLE
Missing/Incomplete include path configuration for glslang (Archlinux)

### ISSUE THREAD

**Issue by yousry** [nvpro-pipeline/VkHLF#6]
For Example Archlinux has a separate glsllang package. 

In /vkhlf/ShaderModule.h it was necessary to change the following:

 #include <vkhlf/Config.h>
 #include <vkhlf/Types.h>
 #include <vkhlf/Reference.h>
-#include <vulkan/../../glslang/glslang/Public/ShaderLang.h>
-#include <vulkan/../../glslang/SPIRV/GlslangToSpv.h>
+#include <glslang/glslang/Public/ShaderLang.h>
+#include <glslang/SPIRV/GlslangToSpv.h>
 #include <vector>

**Comment by asuessenbach** [comment]
Resolved with pull request #13.
