### ISSUE TITLE
Non C++ compilant sources (VC++) 

### ISSUE THREAD

**Issue by yousry** [nvpro-pipeline/VkHLF#7]
The source could neither be compiled with GCC 6.3 or Clang 3.9: 

Unspecialized members are not allowed.

gcc (GCC) 6.3.1

vulkan/VkHLF/vkhlf/Reference.h:52:16: error: explicit specialization in non-namespace scope 'class vkhlf::Reference<T, Ts ...>'
       template<>

clang version 3.9.1

vulkan/VkHLF/vkhlf/Reference.h:53:33: error: cannot specialize a function 'get' within class scope
      std::shared_ptr<T> const& get() const { return m_head; };

**Comment by mtavenrath** [comment]
Issue fixed, closing.
