### ISSUE TITLE
Is GLFW still usefull?

### ISSUE THREAD

**Issue by yousry** [nvpro-pipeline/VkHLF#8]
I used GLFW a lot for Linux/OpenGL but is it still useful as abstraction mechanism for VK? With the "Create Vulkan instance, connect window, setup device" - Workflow it takes me additional 100 lines to open a window and I don't need choose between  GLFW - X11 of GLFW -Wayland libraries which are mutually exclusive under Archlinux.

**Comment by mtavenrath** [comment]
GLFW is useful if you don't want to write your window creation and window handling for multiple platforms. It'd be nice to have a simple abstract window/surface handling for Windows/Waylan/X11/Android inside this project. Though there're more important work to do, so this has to wait a little bit.
